#! /usr/bin/bash

create_table() {
    echo "Creating table '$tableName' in database '$dbName'..."

    while true; do
        clear
        read -p "Enter column name (or type '0' to finish): " columnName
        if [[ "$columnName" == "0" ]]; then
            if [[ $pk -eq 0 ]]; then
                echo "You must define at least one primary key!"
                pause
                continue
            fi
            echo "Finished creating table '$tableName'."
            break
        fi

        if ! validate_column_name "$columnName"; then
            pause
            continue
        fi
        ./checkForRepeatedColumnName $dbName $tableName $columnName
        if [[ $? -eq 0 ]];  # Check if the column name already exists
        then
            echo "Column $columnName already exists in table $tableName. Please choose a different name."
            pause
            continue
        fi

        choose_column_type $dbName $tableName $columnName
    done
}

validate_column_name() {
    local name=$1

    if [[ -z "$name" ]]; then
        echo "You must enter a column name!"
        return 1
    fi

    local result
    result=$(./inputValidator CHARS_ONLY "$name")
    if [[ "$result" != "0" ]]; then
        echo "Column name should be any combination of letters from A to Z or a to z"
        return 1
    fi

    return 0
}

choose_column_type() {
    columnName=$3

    PS3="Choose the type of column '$columnName': "
    select columnType in "INT" "BOOLEAN" "STRING"; do
        case "$columnType" in
            "INT"|"BOOLEAN"|"STRING")
                if [[ $pk -eq 0 && $columnType == "INT" ]]; then
                    read -p "Is this column a primary key? (yes/no): " isPrimaryKey
                    if [[ "$isPrimaryKey" =~ ^[yY]([eE][sS])?$ ]]
                    then
                        pk=1
                        echo "Column $columnName is set as primary key."
                        echo "$columnName:PK" >> "./mydb/$dbName/.$tableName.metadata"
                        break
                    fi
                fi
                echo "Adding column $columnName of type $columnType to table $tableName..."
                echo "$columnName:$columnType" >> "./mydb/$dbName/.$tableName.metadata"
                break
                ;;
            *)
                echo "Invalid column type. Please choose a valid type."
                ;;
        esac
    done
}

pause() {
    read -r -p "Press any key to continue..." -n1 -s
    echo
}

# --- Main Execution ---

if [[ $# -lt 2 ]]
then
    echo "internal error: database name or table name is not provided"
    exit 1
fi

dbName=$1
tableName=$2
pk=0

create_table $dbName $tableName
pause
clear