#!/usr/bin/bash

# ─── ANSI Colors ─────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BLUE='\033[1;34m'
NC='\033[0m' # No Color


while true 
do
    clear
    
    ./listAllDB
    

    read -r -p $'\n📘 [ Info ] Enter database name to connect (or type "exit" to go back): ' dbName
   
    # If input is empty (user just pressed Enter)
    if [[ -z "$dbName" ]]; then
        echo -e "\n${YELLOW}⚠️  [ Warning ] You must enter a database name!${NC}"
        read -r -p $'\n🔁 [ Info ] Press any key to try again...' -n1 -s
        continue
    fi

    # Convert input to lowercase for case-insensitive comparison
    dbNameLower=$(echo "$dbName" | tr '[:upper:]' '[:lower:]')

    if [[ "$dbNameLower" == "exit" ]]; then
        echo -e "${CYAN}🔙 [ Info ] Returning to main menu...${NC}"
        break
    elif [[ -d "mydb/$dbName" ]]; then
        
        
    # Printing letter by letter    
	echo
    msg="🔌 [ Success ] Connecting to database '$dbName'..."
       echo -ne "${GREEN}"
       for ((i=0; i<${#msg}; i++)); do
         echo -ne "${msg:$i:1}"
         sleep 0.02
       done
         echo -e "${NC}"


        sleep 1
	./databaseActions "$dbName"

        echo -e "\n${CYAN}🔄 [ Info ] Returning to Database Menu...${NC}"
	sleep 1
    else
        echo -e "\n${RED}❌ [ Error ] Database '$dbName' does not exist!${NC}"
        read -r -p $'\n🔁 [ Info ] Press any key to try again...' -n1 -s
    fi
done
