#! /usr/bin/bash

while true; do

	clear
	read -p "Enter your Database name or type "0" to go back: " name

	# 0 To go back
	if [[ $name == "0" ]]; then
		read -r -p "Press any key to try again..." -n1 -s
		exit 1
	fi

	# Validate: 4-12 letters only (A-Z, a-z), no spaces, no empty input
	if [[ ! "$name" =~ ^[A-Za-z]{4,12}$ ]]; then
		echo "Database name must be 4–12 letters only (A-Z or a-z), no spaces."
		read -r -p "Press any key to try again..." -n1 -s
		continue
	fi

	# If directory is found
	if [[ -d ./mydb/$name ]]; then
		echo Database with the same name already exists
		continue
	fi
	break
done

mkdir -p ./mydb/$name

exit 0
