#! /usr/bin/bash

while true
do
    read -p "enter your Database name>> or 0 to go back " name

    if [[ $name == "0" ]]
    then
        exit 1
    fi

    resultOfInputValidation=$(./inputValidator CHARS_ONLY $name)
    
    if [[ $resultOfInputValidation == "1" ]]
    then
        echo "only enter letters for the Database name *any compination of letters from A to Z or a to z*"
        continue
    fi

    if [[ -d ./mydb/$name ]]
    then 
        echo Database with the same name already exists
        continue
    fi
    break
done

mkdir -p ./mydb/$name

exit 0