#!/usr/bin/bash

# ─── ANSI Colors ─────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BLUE='\033[1;34m'
NC='\033[0m' # No Color


dbName=$1

while true
do
    clear
    echo -e "${CYAN}📡 [ Info ] Connected to Database '${dbName}'${NC}"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "1) 🧾 Create Table"
    echo -e "\n2) 🗑️  Delete Table"
    echo -e "\n3) 📋 Show Tables"
    echo -e "\n4) 🔍 Select From Table"
    echo -e "\n5) ❌ Delete From Table"
    echo -e "\n6) ➕ Insert To Table"
    echo -e "\n7) ✏️  Update In Table"
    echo -e "\n8) 🚪 Return To Main Menu"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"

    read -p $'📘 [ Action ] Choose an option (1-8): ' action

    case $action in
        1) 
            ./createTable $dbName ;;

        2)
            ./deleteTable $dbName ;;

        3)
            ./showTables $dbName ;;

        4)
            ./selectFromTable $dbName ;;

        5) 
            ./deleteFromTable $dbName ;;

        6) 
            ./insertToTable $dbName ;;

        7)
            ./updateInTable "$dbName" ;;

        8) 
            #echo -e "${CYAN}🔌 [ Info ] Disconnecting from Database '${dbName}'...${NC}"
            
            echo
        msg="🔌 Disconnecting from Database '${dbName}'..."
            echo -ne "${CYAN}"
            for ((i=0; i<${#msg}; i++)); do
              echo -ne "${msg:$i:1}"
              sleep 0.02
            done
              echo -e "${NC}"

            break ;;
	    *) 
            echo -e "\n${YELLOW}⚠️  [ Warning ] Invalid choice! Please enter a number from 1 to 8.${NC}"
            read -n1 -rp $'\n🔁 [ Info ] Press any key to try again...' -s
            ;;
        esac
done


