#! /usr/bin/bash

# 1 -> digits only
# 2 -> characters only
# 3 -> mix of digits & characters

if [[ $# -ne 2 ]]
then
    echo "invalid input"
    exit 1
fi

case $1 in
    DIGITS_ONLY)
        if [[ $2 =~ ^[0-9]+$ ]]
        then
            echo 1 
            
        fi
        ;;
    CHARS_ONLY)
        if [[ $2 =~ ^[A-Za-z]+$ ]]
        then
            echo $2
        fi
        ;;
    CAPS_ONLY)
        if [[ $2 =~ ^[A-Z]+$ ]]
        then
            echo 3
        fi
        ;;
    LOWER_ONLY)
        if [[ $2 =~ ^[a-z]+$ ]]
        then
            echo 4
        fi
        ;;
    MIX)
        if [[ $2 =~ ^[0-9A-Za-z]+$ ]]
        then
            echo 5
        fi
        ;;
    *)
        echo 6
esac
