#! /usr/bin/bash

# 1 -> digits only
# 2 -> characters only
# 3 -> mix of digits & characters

if [[ $# -ne 2 ]]
then
    echo 1
    exit 1
fi

if [[ $# -ne 2 ]]
then
    echo 1
    exit 1
fi

case $1 in
    DIGITS_ONLY | INT | PK)
        if [[ $2 =~ ^[0-9]+$ ]]
        then
            echo 0 
        else
            echo 1
        fi
        ;;
    CHARS_ONLY)
        if [[ $2 =~ ^[A-Za-z]+$ ]]
        then
            echo 0
        else
            echo 1
        fi
        ;;
    CAPS_ONLY)
        if [[ $2 =~ ^[A-Z]+$ ]]
        then
            echo 0
        else
            echo 1
        fi
        ;;
    LOWER_ONLY)
        if [[ $2 =~ ^[a-z]+$ ]]
        then
            echo 0
        else
            echo 1
        fi
        ;;
    MIX | STRING)
        if [[ $2 =~ ^[0-9A-Za-z]+$ ]]
        then
            echo 0
        else
            echo 1
        fi
        ;;
    BOOLEAN)
        if [[ $2 == 'true' || $2 == 'false' ]]
        then
            echo 0
        else
            echo 1
        fi
        ;;
    *)
        echo 1
        echo 1
esac
