#! /usr/bin/bash

# ━━━━━━━━━━━━[ 🎨 Color Definitions ]━━━━━━━━━━━━
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;36m'
NC='\033[0m' # No Color

dbName=$1

tables=$(ls ./mydb/$dbName 2> /dev/null)
if [[ -z "$tables" || $? -ne 0 ]]; then
    echo -e "${RED}❌ No tables found in the database $dbName.${NC}"
    read -n1 -rp "$(echo -e "${YELLOW}⚠️  Press any key to continue...${NC}")" -s
    echo
    exit 1
fi
echo -e "${BLUE}📘 Choose a table to insert into (or type 0 to go back):${NC}"
PS3="> "
select tableName in $tables
do
    if [[ "$REPLY" == "0" ]]; then
        clear
        echo -e "${YELLOW}⚠️  Going back...${NC}"
        exit 1
    fi
    if [[ -n "$tableName" ]]; then
        clear
        echo -e "${BLUE}━━━━━━━━━━━━[ 📘 Inserting into table: $tableName ]━━━━━━━━━━━━${NC}"
        break
    else
        echo -e "${YELLOW}⚠️  Invalid input${NC}"
        read -n1 -rp "$(echo -e "${YELLOW}⚠️  Press any key to continue...${NC}")" -s < /dev/tty
    fi
done


metadataFile="./mydb/$dbName/.$tableName.metadata"
dataFile="./mydb/$dbName/$tableName"

if [[ ! -f "$metadataFile" || ! -f "$dataFile" ]]; then
    echo "$metadataFile or $dataFile does not exist!" >> logs
    echo -e "${RED}❌ Internal error: see logs for more details${NC}"
    read -n1 -rp "$(echo -e "${YELLOW}⚠️  Press any key to continue...${NC}")" -s
    exit 1
fi

declare -i index=0
record=''
while read -r line; do
    index+=1
    if [[ -z "$line" ]]; then
        continue  # skip empty lines
    fi
    columnName=$(echo "$line" | cut -d: -f1)
    columnType=$(echo "$line" | cut -d: -f2)
    isPK=$(echo "$line" | cut -d: -f3)
    if [[ $isPK == "1" ]]; then
        echo -e "${BLUE}📘 Primary key column detected: $columnName${NC}"
    fi
    read -p "$(echo -e "${BLUE}📘 enter value for $columnName of type $columnType:${NC} ")" value < /dev/tty
    inputValidatorResult=$(./inputValidator "$columnType" "$value")
    if [[ "$inputValidatorResult" != "0" ]]; then
        echo -e "${RED}❌ Invalid value for column $columnName of type $columnType.${NC}"
        read -n1 -rp "$(echo -e "${YELLOW}⚠️  Press any key to continue...${NC}")" -s < /dev/tty
        exit 1
    fi
    if [[ "$isPK" == "1" ]]; then
        pkCheckResult=$(./pkCheck "$dbName" "$tableName" "$index" "$value")
        if [[ $? -eq 0 ]]; then
            echo -e "${RED}❌ Primary key value $value already exists in the table.${NC}"
            read -n1 -rp "$(echo -e "${YELLOW}⚠️  Press any key to continue...${NC}")" -s < /dev/tty
            exit 1
        fi
    fi
    record+="$value:"
done < "$metadataFile"

echo "${record%:}" >> "$dataFile"  # remove the trailing colon