#! /usr/bin/bash

# ─── ANSI Colors ─────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color


mydbs=$(./GetAllDbs)
if [[ $? -eq 1 ]]
then 
    echo -e "${RED}❌ [ Error ] There are no databases found.${NC}"
    exit 1
fi

echo -e "${CYAN}\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${CYAN}📋 [ Info ] Available Databases:${NC}"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"

for db in $mydbs
do
    echo -e "${GREEN}➤  $db${NC}"
done
