#!/usr/bin/bash

echo "                |============================| "
echo "                |Welcome To DBMS Bash Project| "
echo "                |============================| "
echo

while true 
do
    clear
    PS3="Enter your choice (1-5): "
    echo "Choose an action:"
    select action in "Create a database" "List all databases" "Connect to a database" "Drop a database" "Exit DBMS"
    do
        case "$action" in
            "Create a database")
                ./createDB
		if [[ $? -eq 0 ]]; then
                    echo "Your database was created successfully!"
                else
                    echo "Failed to create your database."
                fi
                break
                ;;

            "List all databases")
                ./listAllDB
                break
                ;;

            "Connect to a database")
               ./connectToDB
                break
                ;;

            "Drop a database")
                read -p "Enter the name of the database to delete: " dbname
                ./dropDB "$dbname"
                break
                ;;

            "Exit DBMS")
                echo "Exitting.....!"
                exit
                ;;

            *)
                echo "Invalid input. Please choose a number from the menu."
                ;;
        esac
    done

    # Pause before returning to the menu
    read -r -p "Press any key to return to the menu..." -n1 -s
    echo
done

