#! /usr/bin/bash

echo 'Welcome to my_db project'

while true
do
    echo "choose an action"
    echo 'a) create a database'
    echo 'b) list all databases'
    echo 'c) connect to a database'
    echo 'd) drop a database'
    echo 'e) exit'
    read -p '>> ' action
    case $action in
            a)
                ./creatDB
                if [[ $? -eq 0 ]]
                then
                    echo your database created successfuly !!
                else
                    echo failed to creat your Database.
                fi
                ;;        
            b)
                ./ListAllDb
                ;;       
            c)
                echo './connectToDb'
                ;;
            d)
                read -p "enter the name of database to delete: " dbname
                ./dropDB $dbname
                ;;            
            e)
                echo bye!
                exit
                ;;
            *)
                echo invalid input
        esac
done