#! /usr/bin/bash
dbName=$1
tableName=$2
index=$3
pkValue=$4

table="./mydb/$dbName/$tableName"

data=$(cat $table | cut -d: -f$index)

exit $(echo $data | grep -q "$pkValue")  # Check if the primary key value exists