#!/usr/bin/bash

dbName=$1

while true
do
    clear
    echo "Database '$dbName' Table's Menu"
    PS3="Enter your choice (1-8): "

    select action in "Create Table" "Delete Table" "Show Tables" "Select From Table" "Delete From Table" "Insert To Table" "Update In Table" "Return To Main Menu"
    do
        case $action in
            "Create Table") 
                ./createTable $dbName                
                ;;

           "Delete Table") ./deleteTable "$dbName" ; break ;;

            "Show Tables") ./showTables "$dbName" ; break ;;

           "Select From Table") ./selectFromTable "$dbName" ; break ;;

            "Delete From Table") ./deleteFromTable "$dbName" ; break ;;

           "Insert To Table") ./insertToTable $dbName $tableName ; break ;;

            "Update In Table") ./updateInTable "$dbName" ; break ;;

            "Return To Main Menu") echo "Disconnecting from Database $dbName... "; exit 1 ;;
           
	    *) echo "Invalid choice! Please enter a number from 1 to 8." ;;
        esac
    done
#    read -r -p "Press any key to return to the menu..." -n1 -s
done

~

