#! /usr/bin/bash

location=$1

if [[ -z $location ]]
then
    echo "Please provide a location to read the query from."
    exit 1
fi

if [[ ! -f $location ]]
then
    echo "no file found at $location"
    exit 1
fi

lineno=0
while IFS= read -r line
do
    lineno=$((lineno + 1))
    if [[ -z $line ]]
    then
        continue
    fi

    query=${line##[[:space:]]}
    query=${line%%[[:space:]]}

    command=$(echo "$query" | cut -d' ' -f1)
    
    rest=$(echo "$query" | sed "s/$command//")
    rest=${rest##[[:space:]]}
    rest=${rest%%[[:space:]]}

    case $command in
        USE)
            dbname=$(echo "$query" | cut -d' ' -f2)
            if [[ -z "$dbname" ]]; then
                echo "Database name is required"
                exit 1
            elif [[ ! -d "./mydb/$dbname" ]]; then
                echo "Database '$dbname' does not exist."
                exit 1
            fi
            ;;
        CREATE)
        #CREATE TABLE/DATABASE
            case $rest in
                TABLE\ *)
                    if [[ -z "$dbname" ]]; then
                        echo "NO DATABASE SELECTED"
                    fi
                    tableName=$(echo "$rest" | cut -d' ' -f2)
                    if [[ -z "$tableName" ]]; then
                        echo "Table name is required"
                    fi
                    if [[ -f "./mydb/$dbname/$tableName" ]]; then
                        echo "Table '$tableName' already exists in database '$dbname'."
                    else
                        #get table columns and types
                        touch "./mydb/$dbname/$tableName" "./mydb/$dbname/.$tableName.metadata"
                        echo "Table '$tableName' created in database '$dbname'."
                    fi
                    ;;
                DATABASE\ *)
                    newDB=$(echo "$rest" | cut -d' ' -f2)
                    ./createDB "$newDB"
                    ;;
                *)
                    echo "Invalid CREATE command: $rest"
                    ;;
            esac
            ;;
        INSERT)
            echo "Inserting values..."
            ;;
        SELECT)
            echo "Selecting data..."
            ;;
        UPDATE)
            echo "Updating data..."
            ;;
        DELETE)
            echo "Deleting data..."
            ;;
        *)
            echo "Unknown command: $command"
            ;;
    esac
done
